config/routes.rb
Rails.application.routes.draw do
  resources :employees, only: [:new, :create, :confirmation]
  resources :warehouses, only: [:new, :create, :confirmation]
  resources :parts, only: [:index, :create, :new, :edit, :remove, :new_line, :show, :update]
  resources :orders, only: [:index, :new, :create, :show, :confirmation, :edit, :update]

  root to: 'homes#show'

  #homepage routes
  get "/home", to: "homes#show"

  # sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #warehouse routes
  get '/warehouse/:id/confirmation', to: 'warehouses#confirmation', as: 'confirmation'

  #employee routes
  get '/employees/:id/confirmation', to: 'employees#confirmation', as: 'confirm'

  #orders routes
  get '/order/:id/confirmation', to: 'orders#confirmation', as: 'affirm'

  #parts routes
  get '/new_line', to: 'parts#new_line', as: 'new_line'
  put '/parts/:id/remove', to: "parts#remove", as:"remove"

end

app/models/employee.rb
class Employee < ApplicationRecord

  validates :first_name, :last_name, :employee_id, presence: true
  validates :is_manager, inclusion: { in: [ true, false ]}
  has_secure_password

  belongs_to :warehouse
  has_many :removed_parts, foreign_key: :removed_by_id, class_name: :Part
  has_many :received_parts, foreign_key: :received_by_id, class_name: :Part

  has_many :orders

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
    if manager_logged_in?
      @employee = Employee.new()
      render :new
    else
      redirect_to home_path
    end
  end

  def confirmation
    @employee = Employee.find(params[:id])
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to confirm_path(@employee)
    else
      @errors = @employee.errors.full_messages
      render :new
    end
  end

  private
  def employee_params
    if params[:employee][:is_manager] == 'true'
      params[:employee][:is_manager] = true
    elsif params[:employee][:is_manager] == 'false'
      params[:employee][:is_manager] = false
    end
    params.require(:employee).permit(:first_name, :last_name, :employee_id, :password, :warehouse_id, :is_manager)
  end


end

app/views/employees/confirmation.html.erb
<section id="employee-confirm">
  <table>
    <p class="success">You've successfully created a new employee</p>
    <tr>
      <th>Name: </th>
      <td> <%= @employee.first_name + " " + @employee.last_name %> </td>
    </tr>
    <tr>
      <th>Employee ID: </th>
      <td> <%= @employee.employee_id %> </td>
    </tr>
    <tr>
      <th>Location: </th>
      <td> <%= @employee.warehouse.city %> </td>
    </tr>
    <tr>
      <th>Warehouse: </th>
      <td> <%= @employee.warehouse.location_code %> </td>
    </tr>
  </table>
  <% if @employee.is_manager %>
  <p>This employee is granted manager access to this site.</p>
  <% end %>
</section>

app/views/employees/new.html.erb
<section id="new-employee-page">
  <%= form_for @employee, url: employees_path do |f| %>
  <h2>New Employee</h2>

  <% if defined? @errors %>
    <div class="errors">
      <% @errors.each do |error| %>
      <p class="errors"><%= error %></p>
    </div>
      <% end %>
  <% end %>
    <%= f.label :first_name%>
    <%= f.text_field :first_name %>
    <%= f.label :last_name%>
    <%= f.text_field :last_name %>
    <%= f.label 'Employee Id'%>
    <%= f.text_field :employee_id %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label "Warehouse: " %>
    <%= f.select(:warehouse_id) do %>
      <% Warehouse.all.each do |w| %>
      <%= content_tag(:option, w.location_code, value: w.id) %>
      <% end %>
    <% end %>
    <br>
    <br>
    <br>
    <%= f.label(:is_manager, "Check if this employee is a manager")%>
    <%= f.radio_button(:is_manager, 'true', :id => 'true_radio') %>
    <%= f.label(:is_manager_employee, "Check if this employee is not a manager")%>
    <%= f.radio_button(:is_manager, 'false') %>

    <%= f.submit "Create Employee", class: 'submit-button' %>

  <% end %>
</section>