config/routes.rb
Rails.application.routes.draw do
  resources :employees, only: [:new, :create, :confirmation]
  resources :warehouses, only: [:new, :create, :confirmation]
  resources :parts, only: [:index, :create, :new, :edit, :remove, :new_line, :show, :update]
  resources :orders, only: [:index, :new, :create, :show, :confirmation, :edit, :update]

  root to: 'homes#show'

  #homepage routes
  get "/home", to: "homes#show"

  # sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #warehouse routes
  get '/warehouse/:id/confirmation', to: 'warehouses#confirmation', as: 'confirmation'

  #employee routes
  get '/employees/:id/confirmation', to: 'employees#confirmation', as: 'confirm'

  #orders routes
  get '/order/:id/confirmation', to: 'orders#confirmation', as: 'affirm'

  #parts routes
  get '/new_line', to: 'parts#new_line', as: 'new_line'
  put '/parts/:id/remove', to: "parts#remove", as:"remove"

end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :warehouse
  belongs_to :remover, foreign_key: :removed_by_id, class_name: :Employee, optional: true
  belongs_to :receiver, foreign_key: :received_by_id, class_name: :Employee, optional: true
  belongs_to :order, optional: true
  # paginates_per 50

  def self.all_of_type_in_inventory(part_no)
    Part.where(received_by_id: !nil, removed: false, part_no: part_no)
  end

  def self.number_of(part_no, warehouse_id)
    Part.where(received_by_id: !nil, removed: false, part_no: part_no, warehouse_id: warehouse_id).count
  end

  def self.unique_parts_in_inventory(warehouse_id)
    Part.where(warehouse_id: warehouse_id, received_by_id: !nil, removed: false).select('distinct on (name) *')
  end

  def self.number_and_name
    Part.all.map { |part| "#{part.part_no}-#{part.name.capitalize}" }.uniq
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

def index
  if logged_in?
    render :index
  else
    redirect_to '/'
  end
end

def new
end

def create
  if quantity_zero?
    flash[:notice] = "Please enter valid quantities"
    render :new
  else
    @order = Order.last
    create_parts
    @parts = @order.parts
    flash.clear
    redirect_to affirm_path(@order)
  end
end

def new_line
  render '_new_line', layout: false
end

def show
  if logged_in?
    part = Part.find(params[:id])
    # @parts = Part.all_of_type_in_inventory(part.part_no)
    @parts = Part.all_of_type_in_inventory(part.part_no).page params[:page]
  else
    redirect_to '/'
  end
  flash.clear
end

def edit
  @part = Part.find(params[:id])
  if manager_logged_in?
    render :edit
  else
    redirect_to part_path(@part)
  end
end

def update
  flash.clear
  part = Part.find(params[:id])
  @parts = Part.all_of_type_in_inventory(part.part_no)
  if parts_params[:warehouse_id].to_i != part.warehouse_id
    part.update(parts_params)
    flash[:success] = "You transferred Part #{part.id} '#{part.part_no} #{part.name}' to Warehouse #{part.warehouse.location_code}"
    render :show
  else
    flash[:alert] = "This part already resides at #{part.warehouse.location_code}. Please choose another warehouse if you wish to transfer successfully."
    render :show
  end
end

def remove
   part = Part.find(params[:id])
   part.removed = true
   part.removed_by_id = employee_logged_in.id
   part.save
   @parts = Part.all_of_type_in_inventory(part.part_no)
   render :show
 end


private

def parts_params
  params.require(:part).permit(:warehouse_id)
end

end

app/views/parts/_new_line.html.erb
<li>
  <label for="">Part Number</label>
  <select class="" name="part_desc[]">
    <% Part.number_and_name.each do |part| %>
    <option value="<%= part %>"> <%= part %></option>
    <% end %>
  </select>
  <label class="part-quantity" for="">Quantity</label>
  <input class="part-quantity" type="text" name="quantity[]" value="">
</li>

app/views/parts/_parttable.html.erb
  <table class="all-parts">
    <thead>
    <tr>
      <th>Part Number</th>
      <th>Name</th>
      <th>Count</th>
      <th>View</th>
    </tr>
    <% parts.each do |part| %>
      <tr>
        <td><%=part.part_no%></td>
        <td><%= part.name.capitalize %></td>
        <td><%= Part.number_of(part.part_no, warehouse.id) %></td>
        <td><%= link_to "view", part_path(part)%></td>
      </tr>
    <% end %>
  </table>

app/views/parts/index.html.erb
<section id = "inventory-index-page">
  <h1>Master Inventory</h1>
  <% Warehouse.all.each do |w|%>
    <h3><%= w.city %> <%= w.location_code %> :</h3>
    <%= render 'parttable', parts: Part.unique_parts_in_inventory(w.id), warehouse: w %>
  <% end %>
</section>

app/views/parts/new.html.erb
<section id="new-parts-page">
  <%= form_for :part, url: parts_path, html: {class: 'new-parts-form'} do |f| %>
  <h2>Parts Order Form</h2>
  <%= render '/layouts/flash' %>

  <ul class="new-parts-ul">
    <%= render 'new_line' %>
  </ul>

  <%= link_to "Add New Line", new_line_path, class: 'new-part' %>
  <%= f.submit "Place Order", class: 'submit-button order-parts' %>
  <% end %>
</section><!-- end new order page -->

app/views/parts/show.html.erb
<section id="part-show-page">
  <% if @parts[0] == nil %>
    <h3>nothing to show</h3>
  <% else %>
<h3> <%= @parts[0].part_no %>: <%= @parts[0].name.capitalize %> </h3>
  <% if !flash.empty? %>
    <div class="flash">
      <p style="color: green;"><%= flash[:success] %></p>
      <p style="color: red;"><%= flash[:alert] %></p>
    </div>
  <% end %>
  <table >
    <thead>
    <tr>
      <th>Part Id</th>
      <th>Part Number</th>
      <th>Name</th>
      <th>Location</th>
      <th>Remove</th>
      <% if manager_logged_in? %>
        <th>Transfer</th>
      <% end %>
    </tr>
    <% @parts.joins(:warehouse).merge(Warehouse.order(:location_code)).each do |part| %>
      <tr>
        <td><%=part.id%></td>
        <td><%=part.part_no%></td>
        <td><%= part.name.capitalize %></td>
        <td><%= part.warehouse.location_code %></td>
        <td><%= link_to "remove", remove_path(part), method: :put%></td>
        <% if manager_logged_in? %>
          <td><%= link_to "transfer", edit_part_path(part) %> </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <% end %>
<%= paginate @parts %>


  <%= link_to "Back", parts_url,  class: 'back-button' %>
</section>