config/routes.rb
Rails.application.routes.draw do
  resources :employees, only: [:new, :create, :confirmation]
  resources :warehouses, only: [:new, :create, :confirmation]
  resources :parts, only: [:index, :create, :new, :edit, :remove, :new_line, :show, :update]
  resources :orders, only: [:index, :new, :create, :show, :confirmation, :edit, :update]

  root to: 'homes#show'

  #homepage routes
  get "/home", to: "homes#show"

  # sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #warehouse routes
  get '/warehouse/:id/confirmation', to: 'warehouses#confirmation', as: 'confirmation'

  #employee routes
  get '/employees/:id/confirmation', to: 'employees#confirmation', as: 'confirm'

  #orders routes
  get '/order/:id/confirmation', to: 'orders#confirmation', as: 'affirm'

  #parts routes
  get '/new_line', to: 'parts#new_line', as: 'new_line'
  put '/parts/:id/remove', to: "parts#remove", as:"remove"

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :employee
  has_many :parts
  validates :description, presence: true

  def order_name
    self.employee.first_name + " " + self.warehouse.location_code  + " " + self.created_at.to_date.to_s
  end

  def unique_parts
    self.parts.map{ |part| [part.part_no, part.name] }.uniq
  end

  def part_count(part)
    self.parts.where(part_no: part[0]).count
  end
  
  def self.full_orders
    Order.all.select{ |order| order.parts.count > 0 }
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.full_orders
  end

  def create
    order = Order.new(orders_params)
    order.employee = employee_logged_in
    if order.save
      flash.clear
      redirect_to new_part_path
    else
      @errors = order.errors.full_messages
      render :new
    end
  end

  def new
  end

  def show
    @order = Order.find(params[:id])
  end

  def confirmation
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    if quantity_received_zero?
      flash.clear
      @order = Order.find(params[:id])
      flash.alert = "Please enter quantities received"
      render :edit
    else
      update_parts
      flash[:notice] = "Your new inventory has been added!"
      redirect_to root_path
    end
  end

  private
    def orders_params
      params.require(:order).permit(:description, :warehouse_id)
    end
end

app/views/orders/_add_inventory_form.html.erb
<h3>Receive Order Shipment</h3>
  <table>
      <tr>
        <th>Order Description: </th>
            <td> <%= @order.description %> </td>
                <tr>
                  <th>Order Name: </th>
                    <td> <%= @order.order_name %> </td>
                </tr>
              </tr>
              <th>Warehouse: </th>
                <td> <%= @order.warehouse.location_code %> </td>
              </tr>
              <tr>
              </table>
              <h3>Part Summary</h3>
                <% if !flash.empty? %>
                  <div class="flash">
                    <p style="color: red;"><%= flash[:alert] %></p>
                  </div>
                <% end %>
              <table class='order-table-parts'>
              <tr>
                <th>Part Number</th>
                <th>Part Name</th>
                <th>Order Quantity</th>
                <th>Received Quantity</th>
              </tr>
              <tr><%= form_for(@order) do |f| %>
                  <% @order.unique_parts.each do |part| %>
                    <td> <%= part[0] %> </td>
                    <td> <%= part[1] %> </td>
                <td class='quantity'> <%= @order.part_count(part) %> </td>
              <td>
            <input class="part-quantity" type="text" name="quantity_received[]" value="">
          </td>
        </tr>
      <% end %>
    </table>
  <input class="submit-button" type="submit" name="" value="Add Inventory">
<% end %>

app/views/orders/_order_show.html.erb
<h3>Order Summary</h3>
<tr>
  <th>Order Description: </th>
  <td> <%= @order.description %> </td>
</tr>
  <th>Warehouse: </th>
  <td> <%= @order.warehouse.location_code %> </td>
</tr>
<tr>
  <th>Order Name: </th>
  <td> <%= @order.order_name %> </td>
</tr>
<tr>

</table>
<h3>Part Summary</h3>
<table class='order-table-parts'>
<tr>
<th>Part Number</th>
<th>Part Name</th>
<th>Quantity</th>
</tr>
<tr>
  <% @order.unique_parts.each do |part| %>
<td> <%= part[0] %> </td>
<td> <%= part[1] %> </td>
<td class='quantity'> <%= @order.part_count(part) %> </td>
</tr>
<% end %>

app/views/orders/_ordertable.html.erb
  <table>
    <tr>
      <th>Order Number</th>
      <th>Description</th>
      <th>Warehouse</th>
      <th>Add Received Shipment</th>
    </tr>
    <% orders.each do |o| %>
    <tr>
      <td> <%= o.order_name %> </td>
      <td> <%= o.description %> </td>
      <td> <%= o.warehouse.city %> </td>
      <td>  <%= link_to "Select", edit_order_path(o) %> </td>
    </tr>
    <% end %>
  </table>

app/views/orders/confirmation.html.erb
<section id="order-confirm">
  <table class="order-table">
    <p class="success">You've successfully submitted a new order</p>
    <%= render "order_show" %>
  </table>

</section>

app/views/orders/edit.html.erb
<section id="add-inventory-page">
  <table>
    <%= render "add_inventory_form" %>
  </table>

</section>

app/views/orders/index.html.erb
<section id = "order-index-page">
  <h1>Select an Order to Receive</h1>
    <%= render 'ordertable', orders: @orders %>
</section>

app/views/orders/new.html.erb
<section id="new-order-page">
  <%= form_for :order, url: orders_path do |f| %>
  <h2>Begin New Order</h2>

  <% if defined? @errors %>
    <div class="errors">
      <% @errors.each do |error| %>
      <p class="errors"><%= error %></p>
    </div>
      <% end %>
  <% end %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :warehouse %>
    <%= f.select(:warehouse_id) do %>
      <% Warehouse.all.each do |w| %>
      <%= content_tag(:option, w.location_code, value: w.id) %>
      <% end %>
    <% end %>
    <%= f.submit 'Next', class: 'submit-button send-order' %>
  <% end %>
</section><!-- end new order page -->

app/views/orders/show.html.erb
<section id="order-confirm">
  <table>
    <%= render "order_show" %>
  </table>

</section>