config/routes.rb
Rails.application.routes.draw do
  resources :employees, only: [:new, :create, :confirmation]
  resources :warehouses, only: [:new, :create, :confirmation]
  resources :parts, only: [:index, :create, :new, :edit, :remove, :new_line, :show, :update]
  resources :orders, only: [:index, :new, :create, :show, :confirmation, :edit, :update]

  root to: 'homes#show'

  #homepage routes
  get "/home", to: "homes#show"

  # sessions routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #warehouse routes
  get '/warehouse/:id/confirmation', to: 'warehouses#confirmation', as: 'confirmation'

  #employee routes
  get '/employees/:id/confirmation', to: 'employees#confirmation', as: 'confirm'

  #orders routes
  get '/order/:id/confirmation', to: 'orders#confirmation', as: 'affirm'

  #parts routes
  get '/new_line', to: 'parts#new_line', as: 'new_line'
  put '/parts/:id/remove', to: "parts#remove", as:"remove"

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    if logged_in?
      render :home
    else
      redirect_to '/login'
    end
  end
end

app/views/homes/home.html.erb
<section id='homepage'>
  <div id="homepage-container">
    <% if !flash.empty? %>
    <div class="flash">
      <p style="color: green;"><%= flash[:notice] %></p>
    </div>
    <% end %>
    <h1>Inventory Management Portal</h1>
    <nav id="main-nav">
      <ul>
        <li><%= link_to "Inventory", parts_path %></li>
        <!-- FIXME Manage Shipment url replace with :new -->
        <li><%= link_to "Manage Shipment", orders_path %></li>
        <li><%= link_to "Place an Order", new_order_path %></li>
      </ul>
    </nav>
    <% if manager_logged_in? %>
    <h2>For Managers</h2>
    <nav id="manager-nav">
      <ul>
        <li>
          <%= link_to "Add Employee", new_employee_path %>
        </li>
        <li>
          <%= link_to "Add Warehouse", new_warehouse_path %>
        </li>
      </ul>
    </nav>
    <% end %>
    <aside class="site-function">
      <h3>How to use this site</h3>
      <p>Welcome to the Rutherford Rocket Labs Inventory Management Portal. This Website aims to streamline and
        automate inventory process, reduce error and increase organization. Click inventory to see inventory by locaiton. Click manage shipment to view orders and add inventory. Click place order to place order.
      </p>
      <p>
        Each time you use the web portal, you must sign in with your employee number and password. Depending on
        your system configuration, the process for setting up and obtaining them differs. Your department supervisor will assign a randomized numerical value and password
        to sign in, follow the specific directions provided by your system installer and in any emails
        you receive associated with this process.
      </p>
      <p>
        When you finish using the web portal, it is important that you explicitly sign out. If you navigate to a
        different web site without signing out of the web portal, your web portal session remains in effect for
        several minutes. If someone else uses your computer, they might be able to access your system without
        you knowing.
      </p>
    </aside><!-- end site function -->
  </div>
</section>